Patient/EvicenceMVC_Mid/EvicenceMVC/Models/Test.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvicenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.EntryTests = new HashSet<EntryTest>();
        }
    
        public int TestId { get; set; }
        public string TestName { get; set; }
        public decimal Fee { get; set; }
        public bool Available { get; set; }
        public int TestTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntryTest> EntryTests { get; set; }
        public virtual TestType TestType { get; set; }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Models/TestType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvicenceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestType()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int TestTypeId { get; set; }
        public string TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/ViewModels/TestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EvicenceMVC.ViewModels
{
    public class TestViewModel
    {
        [Required]
        public int TestId { get; set; }
        public decimal Fee { get; set; }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Controllers/TestsController.cs
using EvicenceMVC.Models;
using EvicenceMVC.ViewModels;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

namespace EvicenceMVC.Controllers
{
    public class TestsController : Controller
    {

        DCMDbContext db = new DCMDbContext();
        // GET: Tests
        public ActionResult Index()
        {
            return View(db.Tests.Include(t1 => t1.TestType).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateTest()
        {
            ViewBag.TestTypes = db.TestTypes;
            return PartialView("_CreateTest");
        }
        [HttpPost]
        public PartialViewResult CreateTest(Test b)
        {
            Thread.Sleep(3000);
            if (ModelState.IsValid)
            {
                db.Tests.Add(b);
                db.SaveChanges();
                return PartialView("_Success");
            }
            ViewBag.TestTypes = db.TestTypes;
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.TestTypes = db.TestTypes;
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditTest(int id)
        {
            ViewBag.TestTypes = db.TestTypes;
            var b = db.Tests.First(x => x.TestId == id);
            return PartialView("_EditTest", b);
        }
        [HttpPost]
        public PartialViewResult EditTest(Test b)
        {
            Thread.Sleep(4000);
            if (ModelState.IsValid)
            {
                db.Entry(b).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            ViewBag.TestTypes = db.TestTypes;
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.Tests.First(x => x.TestId == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int TestId)
        {
            var b = new Test { TestId = TestId };
            db.Entry(b).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/Create.cshtml
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-primary">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <h3>Add new Test</h3>
        @Html.Action("CreateTest")
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{

    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset')
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>

}

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/Delete.cshtml
@model EvicenceMVC.Models.Test
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3>Cofirm delete</h3>
    </div>
    @Html.HiddenFor(x => x.TestId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.TestName)
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Fee, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.Fee)
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestTypeId, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.TestTypeId)
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Available, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.Available, new { @class = "form-check", disabled = "true" })
        </div>
    </div>
    <div class="form-group row mb-1">

        @using (Html.BeginForm())
        {
            @Html.HiddenFor(x => x.TestId)
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
        }
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-primary">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <h3>Edit</h3>
        @Html.Action("EditTest", new { id = ViewBag.Id })
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
        $("#StartDate").val(formatDate($("#StartDate").val()));
        if ($("#EndDate").val() != "") {
            $("#EndDate").val(formatDate($("#EndDate").val()));
        }
        function formatDate(date) {
            var d = new Date(date),
                month = '' + (d.getMonth() + 1),
                day = '' + d.getDate(),
                year = d.getFullYear();

            if (month.length < 2)
                month = '0' + month;
            if (day.length < 2)
                day = '0' + day;

            return [year, month, day].join('-');
        }
    </script>
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/Index.cshtml
@model IEnumerable<EvicenceMVC.Models.Test>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Tests</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add New", "Create", "Tests", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.TestName)</th>
                    <th>@Html.DisplayNameFor(x => x.Fee)</th>
                    <th>@Html.DisplayNameFor(x => x.TestTypeId)</th>
                    <th>@Html.DisplayNameFor(x => x.Available)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var d in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => d.TestName)</td>
                        <td>@Html.DisplayFor(x => d.Fee)</td>
                        <td>@Html.DisplayFor(x => d.TestType.TypeName)</td>
                        <td>@(d.Available ? "Yes": "No")</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Tests", new { id = d.TestId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Tests", new {id=d.TestId})" class="btn btn-danger btn-sm @(d.EntryTests.Count > 0 ? "disabled" :"")">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/_CreateTest.cshtml
@model EvicenceMVC.Models.Test
@using (Ajax.BeginForm("CreateTest", "Tests", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    OnSuccess = "onSuccess",
    LoadingElementId = "spinner"
}, new { id = "f" }))
{
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.TestName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.TestName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Fee, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Fee, new { @class = "form-control form-control-sm", type = "number" })
            @Html.ValidationMessageFor(x => x.Fee, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestTypeId, new { @class = "col-form-label col-2" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.TestTypeId, new SelectList(ViewBag.TestTypes, "TestTypeId", "TypeName"), "Select", new { @class = "form-select select" })
            @Html.ValidationMessageFor(x => x.TestTypeId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Available, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.Available, new { @class = "form-check" })
            @Html.ValidationMessageFor(x => x.Available, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Tests/_EditTest.cshtml
@model EvicenceMVC.Models.Test
@using (Ajax.BeginForm("EditTest", "Tests", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    LoadingElementId = "spinner"

}, new { id = "f" }))
{
    @Html.HiddenFor(x => x.TestId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.TestName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.TestName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Fee, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Fee, new { @class = "form-control form-control-sm", type = "number" })
            @Html.ValidationMessageFor(x => x.Fee, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.TestTypeId, new { @class = "col-form-label col-2" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.TestTypeId, new SelectList(ViewBag.TestTypes, "TestTypeId", "TypeName"), "Select", new { @class = "form-select select" })
            @Html.ValidationMessageFor(x => x.TestTypeId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Available, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.Available, new { @class = "form-check" })
            @Html.ValidationMessageFor(x => x.Available, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}