Patient/EvicenceMVC_Mid/EvicenceMVC/Controllers/TestEntriesController.cs
using EvicenceMVC.Models;
using EvicenceMVC.ViewModels;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvicenceMVC.Controllers
{
    public class TestEntriesController : Controller
    {
        private readonly DCMDbContext db = new DCMDbContext();
        // GET: TestEntries
        public ActionResult Index()
        {
            var data = db.TestEntries
                .Include(x => x.EntryTests.Select(y => y.Test))
                .ToList();

            return View(data.OrderByDescending(x=>x.TestEntryId).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.Tests = db.Tests.ToList();
            var data = new TestEntryInputModel();
            data.Tests.Add(new TestViewModel());
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(TestEntryInputModel model, int[] TestId)
        {
            if (ModelState.IsValid)
            {
                var et = new TestEntry
                {
                    PatientName = model.PatientName,
                    Age = model.Age,
                    MobileNo = model.MobileNo,
                    TestDate = model.TestDate,
                    DueDate = model.DueDate
                };
                foreach (var x in TestId)
                {
                    et.EntryTests.Add(new EntryTest { TestId = x });
                }
                if (model.Picture.ContentLength > 0)
                {
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string fileName = Guid.NewGuid() + ext;
                    model.Picture.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
                    et.Picture = fileName;
                }
                db.TestEntries.Add(et);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Tests = db.Tests.ToList();

            return View(model);
        }
        public JsonResult GetFee(int id)
        {
            var t = db.Tests.FirstOrDefault(x => x.TestId == id);
            return Json(t == null ? 0 : t.Fee);
        }
        public ActionResult CreateNewField(TestEntryInputModel data)
        {
            ViewBag.Tests = db.Tests.ToList();
            data.Tests.Add(new TestViewModel());
            return PartialView(data);
        }
        public ActionResult CreateV1()
        {

            return View();
        }
        public PartialViewResult CreateTestEntry()
        {
            ViewBag.Tests = db.Tests.ToList();

            return PartialView("_TestEntry");
        }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Controllers/TestTypesController.cs
using EvicenceMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace EvicenceMVC.Controllers
{
    public class TestTypesController : Controller
    {
        DCMDbContext db = new DCMDbContext();
        // GET: TestType
        public ActionResult Index()
        {
            return View(db.TestTypes.Include(tt => tt.Tests).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateTestType()
        {

            return PartialView("_CreateTestType");
        }
        [HttpPost]
        public PartialViewResult CreateTestType(TestType b)
        {
            Thread.Sleep(3000);
            if (ModelState.IsValid)
            {
                db.TestTypes.Add(b);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditTestType(int id)
        {
            var b = db.TestTypes.First(x => x.TestTypeId == id);
            return PartialView("_EditTestType", b);
        }
        [HttpPost]
        public PartialViewResult EditTestType(TestType b)
        {
            Thread.Sleep(4000);
            if (ModelState.IsValid)
            {
                db.Entry(b).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.TestTypes.First(x => x.TestTypeId == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int TestTypeId)
        {
            var b = new TestType { TestTypeId = TestTypeId };
            db.Entry(b).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Patient/EvicenceMVC_Mid/EvicenceMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>

        .main {
            padding-top: 20px;
            /*height: calc(100vh - 140px);*/
        }
    </style>
    @RenderSection("styles", false)

</head>
<body>
    <nav class="navbar navbar-light text-white bg-success navbar-expand-md text-center  shadow-sm">
        <div class="container-fluid text-center">
            <span class="navbar-brand text-white">Patient</span>
            <div class="navbar-collapse collapse text-center">
                <ul class="navbar-nav nav text-white text-center ">
                    <li class="nav-item">
                        @Html.ActionLink("Report", "PatientList", "Home", new { }, new { @class = "nav-link text-white text-center" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Tests", "Index", "Tests", new { }, new { @class = "nav-link text-white text-center" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Test Types", "Index", "TestTypes", new { }, new { @class = "nav-link text-white text-center" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Test Entries", "Index", "TestEntries", new { }, new { @class = "nav-link text-white text-center " })
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <br />
    <br />
    <footer class="fixed-bottom bg-success text-center">
        <a class=" text-white">www.patient.com</a>
    </footer>
    <section class="container-fluid main">
        @RenderBody()
    </section>
    @*<footer class="container-fluid">
            <p>Oh My Foot</p>
        </footer>*@
    @RenderSection("scripts", false)
</body>
</html>